### ISSUE TITLE
[error?] No check for partial quest completion?

### ISSUE THREAD

**Issue by MolunSIB** [dvize/GTFO#2]
I already returned this controller in a previous raid, but it is still highlighted on the screen.
![image](https://github.com/dvize/GTFO/assets/70684659/b5235a7b-57cc-4d72-b950-10db8fc65195)
![image](https://github.com/dvize/GTFO/assets/70684659/3c66fb73-221f-4b45-b1ee-fae6eb816ab3)

**Comment by MolunSIB** [comment]
Similarly, I did it in the last raid
![image](https://github.com/dvize/GTFO/assets/70684659/729f5353-126e-4baf-a833-637ad0a00886)
![image](https://github.com/dvize/GTFO/assets/70684659/9a54554f-c0b1-4a28-a10a-164b9e049754)

**Comment by dvize** [comment]
This is resolved in latest update
